### ISSUE TITLE
求助大佬！我无法转换到应用所需的音频格式

### ISSUE THREAD

**Issue by SUNbrightness** [DavaiZa/AudioSearch#2]
我自己的音频进入PCM16MonoParser.parse 这个方法老报错。我已经尝试使用audition + ffmpeg 将我音频转为了PCM WAV，16-bit，单声道，44100Hz
但是音频的原信息始终无法去掉，到下图这里就GG啦
rfile.seek(36);
        if (rfile.readShort() != (short) 0x0000) {
            throw new RuntimeException("The audio has extra parameters in its \"fmt \" block");
}
求助大佬，我的音频基础知识不太好
有没有推荐的方式能去除我的音频元数据，让我可以使用这个程序？
我看大佬这个类的代码不是太理解，大概明白是取到了wav的data数据，难道java没有提供现成的工具包直接获取wav的data数据吗？

**Comment by winston-wen** [comment]
肯定有的，你搜一下。音频格式发展到现在已经有了各种各样的格式头，自己写解析程序肯定是不必要的。当初我写这么个程序，只是用来锻炼助教班的学生。

**Comment by winston-wen** [comment]
你需要找到一个java库，把wav读取成振幅数组。数组的每个元素是振幅，每44100个相邻元素是一秒的声音。随便什么音频库应该都有这种功能。

**Comment by SUNbrightness** [comment]
谢谢大佬，根据你的提示我找到了对应的类javax.sound.sampled直接提取就可以了
我看你在知乎里说的"在马尔可夫链、CNN、RNN等更加先进的机器学习方法面前，Shazam算法该退休了"。理论上是这样的，我在github上看到的Shazam都是好几年前的项目的。为什么我找不到机器学习的声音比对算法呢。githuib上目前的声音比对项目好像都是Shazam的。

**Comment by winston-wen** [comment]
那个时候我还图样图森破，而且在这个代码之后再也没搞音频方向。这我回答不了你。

**Comment by SUNbrightness** [comment]
ok谢谢了
